### ISSUE TITLE
Сломаный html + советы по разметке

### ISSUE THREAD

**Issue by justvorona** [nikita080428/mail-2.0#2]
#### Description
У карточек в <img> стоят закрывающие тэги.
`> 258 |           <img src="assets/image/fish_girl.png" alt="Девушка на рыбалке.png" ></img>`

#### Советы
- [x] #3
  - Больше похоже на `<nav>`
  - `<b>` еще понятно зачем, а зачем `<p>`?
- [x] Реклама
  - Сюда подойдет тэг `<aside>`
  - `class="reclame_block"` Лучше переименовать по-английски (переводчик в помощь)
  - `alt="Реклама кота.jpg"` - `.jpg` не надо:)
-  [x] Погода
  - А вот это уже не `<aside>` а скорее секция

**Comment by nikita080428** [comment]
Первый task выполнен, сегодня ночью сделаю еще два и наконец доделаю
позиционирование + карточки снизу + якорную ссылку.
